### ISSUE TITLE
Size helper  applied to value from data

### ISSUE THREAD

**Issue by rragan** [linkedin/dustjs-helpers#46]
If I write {@size key="{str} /}, the value output is a constant regardless of the length of the string in str. That is because a {key} value results in a function being passed to the helper and it computes the length of that function converted to a string -- a particularly useless behavior.  

I would suggest size be changed to run tap on any key input that is a function and compute the length of the result.

What say you who built the size helper? Is this a bug or an oversight?

**Comment by sethkinast** [comment]
We should do this only for `__dustBody` functions.

**Comment by sethkinast** [comment]
So I actually changed my viewpoint on this one as I was writing the fix.

This is different than the `{?exists}` case because with `{@size}` you are specifically asking to operate on the result of the function, since stringifying the function and returning that size makes no sense.

The fix is part of #129 (the fix in the PR referenced here is not correct, since a function might return an Object or similar).
